config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  get "/articles", to: "articles#index"
  post "/articles/create_article", to: "articles#create"
  get "/articles/create_article", to: "articles#new"
  get "/articles/:slug", to: "articles#show"
  put "/articles/:slug/edit", to: "articles#update", as: "articles_update"
  get "/articles/:slug/edit", to: "articles#edit"
  delete "/articles/:id", to: "articles#destroy" , as: "articles_destroy"
  




  get "/categories", to: "category#index"
  post "/categories/create_category", to: "category#create"
  get "/categories/create_category", to: "category#new"
  get "/category/:id", to: "category#show"
  put "/category/:id/edit", to: "category#update", as: "category_update"
  get "/category/:id/edit", to: "category#edit"
  delete "/category/:id", to: "category#destroy", as: "category_destroy"

  # resources :category 




  # resources :articles
  # resources :users
  # resources :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one_attached :featured_image
  after_validation :set_slug, only: [:create, :update]

  private
  def set_slug
    self.slug = title.to_s.parameterize
    end 

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles , :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @Article = Article.all
    end

    def show
        @Article = Article.find_by(slug: params[:slug])
        if !@Article
            redirect_to "/articles"
        else
            @Article
        end
    end

    def create
        @Article = Article.new(article_params)
        if @Article.save
            redirect_to "/articles", notice: "Article was successfully created."
          else
            render :new, notice: "Not created"
          end
    end
    def new
        @Article = Article.new
    end
    def edit
        @Article = Article.find_by(slug: params[:slug])
    end

    def update
        @Article = Article.find_by(slug: params[:slug])
        @updated=@Article.update(article_params)
        if @updated
            redirect_to "/articles", notice: "Updated Successfully"
        else
           render @Article, notice: "Please try again"
        end
    end

    def destroy
        @Article = Article.find_by(id: params[:id])
        @Article.destroy
            redirect_to "/articles"
    end

    def article_params
        params.require(:article).permit(:title, :body, :featured_image, :tags, :category_id, :user_id, :isPublished)
      end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
    def index
        @Category = Category.all
    end

    def show
        @Category = Category.find(params[:id])
        if !@Category
            redirect_to "/categories"
        else
            @Category
        end
    end

    def create
        @Category = Category.new(category_params)
        if @Category.save
            redirect_to "/categories", notice: "Category was successfully created."
          else
            render :new, notice: "Not created"
          end
    end
    def new
        @Category = Category.new
    end

    def edit
        @Category = Category.find_by(id: params[:id])
    end

    def update
        @Category = Category.find_by(id: params[:id]).update(category_params)
        redirect_to "/categories", notice: "Updated Successfully"
    end


    def destroy
        @Category = Category.find_by(id: params[:id])
        @Category.destroy
        redirect_to "/categories"
    end


    def category_params
        params.require(:category).permit(:category_title)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<section>
    <%= form_with model: @Article, url: articles_update_path, method: :put do |form|%>
    <div class="mb-3">
        <%= form.label :title%>
        <%= form.text_field :title, class: "form-control", placeholder: "Title"%>
    </div>
    <div class="mb-3">
        <%= form.label :body%>
        <%= form.text_area :body, class: "tinymce", placeholder: "Write about...."%>
    </div>
    <div class="mb-3">
        <%= form.label :user_id %>
        <%= form.select :user_id, options_for_select(User.all.map { |c| [c.name, c.id] }), class: "form-control", placeholder: "User"%>
    </div>
    <div class="mb-3">
        <%= form.label :tags%>
        <%= form.text_field :tags, class: "form-control", placeholder: "Enter tags for seo"%>
    </div>
    <div class="mb-3">
        <%= form.label :category_id%>
        <%= form.select :category_id, options_for_select(Category.all.map { |c| [c.category_title, c.id] }), class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :isPublished %>
        <%= form.check_box :isPublished , class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :featured_image %>
        <%= form.file_field  :featured_image , class: "form-control"%>
    </div>

    <div class="mb-3">
        <%= form.submit "Submit", class: " bg-blue-500 hover:bg-blue-700 text-black font-bold py-2 px-4 rounded btn btn-blue"%>
    </div>
    <% end %>
</section>

app/views/articles/index.html.erb
<section class="container">
    <ul class="flex ml-auto">
        <a class="font-bold text-xl mr-4" href="/articles/create_article">Add Article</a>
        <a class="font-bold text-xl " href="/categories/create_category">Add Category</a>
    </ul>
    <h1 class="font-bold text-xl">Latest Articles</h1>
    <div class="flex">
        <% @Article.each do |article| %>
        <div class="max-w-sm mr-5 mt-5 bg-gray border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <a href="/articles/<%= article.slug %>">
                <img height="200px" class="rounded-t-lg" src=<%= url_for(article.featured_image) %>></a>
            <div class="p-5">
                <a href="#">
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= article.title.first(20)%></h5>
                </a>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= article.body.first(200).html_safe %></p>
                <a href="/articles/<%= article.slug %>" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    Read more
                    <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                    </svg>
                </a>
            </div>
        </div>
        <% end %>
        
    </div>
</section>

app/views/articles/new.html.erb
<section>
    <%= form_with model: @Article, url: articles_create_article_path do |form|%>
    <div class="mb-3">
        <%= form.label :title%>
        <%= form.text_field :title, class: "form-control", placeholder: "Title"%>
    </div>
    <div class="mb-3">
        <%= form.label :body%>
        <%= form.text_area :body, class: "tinymce", placeholder: "Write about...."%>
    </div>
    <div class="mb-3">
        <%= form.label :user_id %>
        <%= form.select :user_id, options_for_select(User.all.map { |c| [c.name, c.id] }), class: "form-control", placeholder: "User"%>
    </div>
    <div class="mb-3">
        <%= form.label :tags%>
        <%= form.text_field :tags, class: "form-control", placeholder: "Enter tags for seo"%>
    </div>
    <div class="mb-3">
        <%= form.label :category_id%>
        <%= form.select :category_id, options_for_select(Category.all.map { |c| [c.category_title, c.id] }), class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :isPublished %>
        <%= form.check_box :isPublished , class: "form-control"%>
    </div>
    <div class="mb-3">
        <%= form.label :featured_image %>
        <%= form.file_field  :featured_image , class: "form-control"%>
    </div>

    <div class="mb-3">
        <%= form.submit "Submit", class: " bg-blue-500 hover:bg-blue-700 text-black font-bold py-2 px-4 rounded btn btn-blue"%>
    </div>
    <% end %>
</section>

app/views/articles/show.html.erb
<div>
    <a href="<%=@Article.slug%>/edit">Edit Articles</a>
    <h1> <%= @Article.title %> </h1> 
    <%= link_to "Destroy", articles_destroy_path(@Article), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

    <img src="<%= url_for(@Article.featured_image) %>" alt="">
    <p><%= @Article.category_id %></p>
    <p><b><%= @Article.user_id %></b></p>
    <p><%= @Article.body.html_safe %> </p>
    <p><%= @Article.tags %></p>
</div>

app/views/category/edit.html.erb
<section>
    <%= form_with model: @Category, url: category_update_path, method: :put do |form|%>
    <div class="mb-3">
        <%= form.label :category_title%>
        <%= form.text_field :category_title, class: "form-control", placeholder: "Title"%>
    </div>
    <div class="mb-3">
        <%= form.submit "Submit", class: " bg-blue-500 hover:bg-blue-700 text-black font-bold py-2 px-4 rounded btn btn-blue"%>
    </div>
    <% end %>
</section>

app/views/category/index.html.erb
<div>
    <b class="mb-2">Categories</b>
    <% @Category.each do |category| %>
   <h1><%= category.id %>: <%= category.category_title %> </h1> 
   <% end %>
</div>

app/views/category/new.html.erb
<section>
    <%= form_with model: @Category, url: categories_create_category_path do |form|%>
    <div class="mb-3">
        <%= form.label :category_title%>
        <%= form.text_field :category_title, class: "form-control", placeholder: "Title"%>
    </div>
    <div class="mb-3">
        <%= form.submit "Submit", class: " bg-blue-500 hover:bg-blue-700 text-black font-bold py-2 px-4 rounded btn btn-blue"%>
    </div>
    <% end %>
</section>

app/views/category/show.html.erb
<div>
    <h1><%= @Category.id %>: <%= @Category.category_title %> </h1> 
    <%= link_to "Destroy", category_destroy_path(@Category), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
      tinymce.init({
        selector: '.tinymce',
        height: 500,
        menubar: false,
        plugins: [
          'a11ychecker','advlist','advcode','advtable','autolink','checklist','export',
          'lists','link','image','charmap','preview','anchor','searchreplace','visualblocks',
          'powerpaste','fullscreen','formatpainter','insertdatetime','media','table','help','wordcount'
        ],
        toolbar: 'undo redo | casechange blocks | bold italic backcolor | ' +
          'alignleft aligncenter alignright alignjustify | ' +
          'bullist numlist checklist outdent indent | removeformat | a11ycheck code table help'
      });
    </script>
      
  </head>

  <body>
    
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>